<?php
$mobo = [

  1 => 
  array (
    'Brand' => 'MSI',
    'Model' => 'Z97 PC Mate',
    ' CPU Socket Type' => 'LGA1150',
    'CPU Type' => 'Core i7 / i5 / i3 / Pentium / Celeron (LGA1150)',
    ' Chipset' => 'Intel Z97',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 3000/2800/2666/2600/2400/2200/2133/2000/1866/1600/1333/1066',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '2',
    'PCI Slots' => '2',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 2,
  ),
  3 => 
  array (
    'Brand' => 'ASRock',
    'Model' => 'Fatal1ty Z97 Killer',
    ' CPU Socket Type' => 'LGA1150',
    'CPU Type' => 'Core i7 / i5 / i3 / Pentium / Celeron (LGA1150)',
    ' Chipset' => 'Intel Z97',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 3200/2933/2800/2400/2133/1866/1600/1333/1066',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '2',
    'PCI Slots' => '2',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => '1',
    'SATA Express' => '1',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 2,
  ),

  10 => 
  array (
    'Brand' => 'Gigabyte',
    'Model' => 'GA-Z97-HD3',
    ' CPU Socket Type' => 'LGA1150',
    'CPU Type' => 'Core i7 / i5 / i3 / Pentium / Celeron (LGA1150)',
    ' Chipset' => 'Intel Z97',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 3100/3000/2933/2800/2666/2600/2500/2400/2200/2133/2000/1866/1800/1600/1333',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '2',
    'PCI Slots' => '2',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 2,
  ),
  11 => 
  array (
    'Brand' => 'ASRock',
    'Model' => 'Z97 Pro4',
    ' CPU Socket Type' => 'LGA1150',
    'CPU Type' => 'Core i7 / i5 / i3 / Pentium / Celeron (LGA1150)',
    ' Chipset' => 'Intel Z97',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 3100/2933/2800/2400/2133/1866/1600/1333/1066',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '2',
    'PCI Slots' => '2',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => '1',
    'SATA Express' => '1',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 2,
  ),
  12 => 
  array (
    'Brand' => 'ASRock',
    'Model' => 'Z97 Pro3',
    ' CPU Socket Type' => 'LGA1150',
    'CPU Type' => 'Core i7 / i5 / i3 / Pentium / Celeron (LGA1150)',
    ' Chipset' => 'Intel Z97',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 3100/2933/2800/2400/2133/1866/1600/1333/1066',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '3',
    'PCI Slots' => '2',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 1,
  ),
  15 => 
  array (
    'Brand' => 'Gigabyte',
    'Model' => 'GA-Z97X-Gaming 7',
    ' CPU Socket Type' => 'LGA1150',
    'CPU Type' => 'Core i7 / i5 / i3 / Pentium / Celeron (LGA1150)',
    ' Chipset' => 'Intel Z97',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 3200/3100/3000/2933/2800/2666/2600/2500/2400/2200/2133/2000/1866/1800/1600/1333',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '3',
    'PCI Slots' => '1',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '8',
    'SATA RAID' => 0,
    'M.2' => '1',
    'SATA Express' => '1',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 1,
  ),
  18 => 
  array (
    'Brand' => 'Gigabyte',
    'Model' => 'GA-Z97X-SLI',
    ' CPU Socket Type' => 'LGA1150',
    'CPU Type' => 'Core i7 / i5 / i3 / Pentium / Celeron (LGA1150)',
    ' Chipset' => 'Intel Z97',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 3000/2933/2800/2666/2600/2500/2400/2200/2133/2000/1866/1800/1600/1333',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '3',
    'PCI Slots' => '2',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => '1',
    'SATA Express' => '1',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 2,
  ),
  26 => 
  array (
    'Brand' => 'Gigabyte',
    'Model' => 'GA-Z97X-Gaming 3',
    ' CPU Socket Type' => 'LGA1150',
    'CPU Type' => 'Core i7 / i5 / i3 / Pentium / Celeron (LGA1150)',
    ' Chipset' => 'Intel Z97',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 3200/3100/3000/2933/2800/2666/2600/2500/2400/2200/2133/2000/1866/1800/1600/1333',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '3',
    'PCI Slots' => '1',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => '1',
    'SATA Express' => '1',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 2,
  ),
  33 => 
  array (
    'Brand' => 'Asus',
    'Model' => 'Z170-A',
    ' CPU Socket Type' => 'LGA1151',
    'CPU Type' => 'Core i7 / i5 / i3 / Pentium / Celeron (LGA1151)',
    ' Chipset' => 'Intel Z170',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR4 3400/3333/3200/3100/3000/2933/2800/2666/2600/2400/2133',
    'Maximum Memory Supported' => '64',
    'PCI Express x1' => '3',
    'PCI Slots' => '1',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => '1',
    'SATA Express' => '1',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '288-pin',
    'pci_x16_slot' => 2,
  ),
  51 => 
  array (
    'Brand' => 'MSI',
    'Model' => 'Z97S SLI Krait Edition',
    ' CPU Socket Type' => 'LGA1150',
    'CPU Type' => 'Core i7 / i5 / i3 / Pentium / Celeron (LGA1150)',
    ' Chipset' => 'Intel Z97',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 3200/3100/3000/2800/2666/2600/2400/2200/2133/2000/1866/1600/1333/1066',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '3',
    'PCI Slots' => '2',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => '1',
    'SATA Express' => '1',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 2,
  ),


  110 => 
  array (
    'Brand' => 'Asus',
    'Model' => 'H81M-C/CSM/C/SI',
    ' CPU Socket Type' => 'LGA1150',
    'CPU Type' => '4th Generation Core i7/Core i5/Core i3/Pentium/Celeron',
    ' Chipset' => 'Intel H81',
    'Number of Memory Slots' => '2',
    'Memory Standard' => 'DDR3 1600/1333/1066',
    'Maximum Memory Supported' => '16',
    'PCI Express x1' => '2',
    'PCI Slots' => '1',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '2',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => '2',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'Micro ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 1,
  ),
  
  120 => 
  array (
    'Brand' => 'MSI',
    'Model' => 'Z170A GAMING PRO',
    ' CPU Socket Type' => 'LGA1151',
    'CPU Type' => 'Core i7 / i5 / i3 / Pentium / Celeron (LGA1151)',
    ' Chipset' => 'Intel Z170',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR4 3600/3200/3000/2800/2600/2400/2133',
    'Maximum Memory Supported' => '64',
    'PCI Express x1' => '3',
    'PCI Slots' => '1',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '4',
    'SATA RAID' => 0,
    'M.2' => '1',
    'SATA Express' => '1',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '288-pin',
    'pci_x16_slot' => 3,
  ),
 
 


  191 => 
  array (
    'Brand' => 'Asus',
    'Model' => 'B85M-E/CSM',
    ' CPU Socket Type' => 'LGA1150',
    'CPU Type' => 'Core i7 / i5 / i3 / Pentium / Celeron (LGA1150)',
    ' Chipset' => 'Intel B85',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 1600/1333/1066',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '1',
    'PCI Slots' => '1',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '4',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => '2',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'Micro ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 2,
  ),
 

  208 => 
  array (
    'Brand' => 'Asus',
    'Model' => 'H81M-C/CSM',
    ' CPU Socket Type' => 'LGA1150',
    'CPU Type' => '4th Generation Core i7/Core i5/Core i3/Pentium/Celeron',
    ' Chipset' => 'Intel H81',
    'Number of Memory Slots' => '2',
    'Memory Standard' => 'DDR3 1600/1333/1066',
    'Maximum Memory Supported' => '16',
    'PCI Express x1' => '2',
    'PCI Slots' => '1',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '2',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => '2',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'Micro ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 1,
  ),
 
  230 => 
  array (
    'Brand' => 'Asus',
    'Model' => 'B85M-E/CSM/SI',
    ' CPU Socket Type' => 'LGA1150',
    'CPU Type' => 'Core i7 / i5 / i3 / Pentium / Celeron (LGA1150)',
    ' Chipset' => 'Intel B85',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 1600/1333/1066',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '1',
    'PCI Slots' => '1',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '4',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => '2',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'Micro ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 2,
  ),
  231 => 
  array (
    'Brand' => 'MSI',
    'Model' => 'Z170A GAMING M3',
    ' CPU Socket Type' => 'LGA1151',
    'CPU Type' => 'Core i7 / i5 / i3 / Pentium / Celeron (LGA1151)',
    ' Chipset' => 'Intel Z170',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR4 3600/3200/3000/2800/2600/2400/2133',
    'Maximum Memory Supported' => '64',
    'PCI Express x1' => '2',
    'PCI Slots' => '3',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => '1',
    'SATA Express' => '2',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '288-pin',
    'pci_x16_slot' => 2,
  ),
  234 => 
  array (
    'Brand' => 'MSI',
    'Model' => 'Z170A KRAIT GAMING',
    ' CPU Socket Type' => 'LGA1151',
    'CPU Type' => 'Core i7 / i5 / i3 / Pentium / Celeron (LGA1151)',
    ' Chipset' => 'Intel Z170',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR4 3600/3200/3000/2800/2600/2400/2133',
    'Maximum Memory Supported' => '64',
    'PCI Express x1' => '3',
    'PCI Slots' => '1',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '4',
    'SATA RAID' => 0,
    'M.2' => '1',
    'SATA Express' => '1',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '288-pin',
    'pci_x16_slot' => 3,
  ),
 
  246 => 
  array (
    'Brand' => 'Asus',
    'Model' => 'Z87-A',
    ' CPU Socket Type' => 'LGA1150',
    'CPU Type' => 'Core i7 / i5 / i3 / Pentium / Celeron (LGA1150)',
    ' Chipset' => 'Intel Z87',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 3000/2933/2800/2666/2600/2500/2400/2200/2133/2000/1866/1800/1600/1333',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '2',
    'PCI Slots' => '2',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 3,
  ),
  
  
  253 => 
  array (
    'Brand' => 'MSI',
    'Model' => 'CSM-Q87M-E43',
    ' CPU Socket Type' => 'LGA1150',
    'CPU Type' => '4th Generation Intel Corei7/Corei5/Corei3/Pentium/Celeron (LGA 1150)',
    ' Chipset' => 'Intel Q87',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 1600/1333/1066',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '2',
    'PCI Slots' => '1',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'Micro ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 1,
  ),
  
  
  264 => 
  array (
    'Brand' => 'MSI',
    'Model' => 'B85-G41 PC Mate',
    ' CPU Socket Type' => 'LGA1150',
    'CPU Type' => '4th-generation Core i3,i5,i7,Pentium,Celeron(LGA1150)',
    ' Chipset' => 'Intel B85',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 1066/1333/1600',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '2',
    'PCI Slots' => '2',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '4',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => '2',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 2,
  ),
  268 => 
  array (
    'Brand' => 'ASRock',
    'Model' => 'Z97 Anniversary',
    ' CPU Socket Type' => 'LGA1150',
    'CPU Type' => 'Core i7 / i5 / i3 / Pentium / Celeron (LGA1150)',
    ' Chipset' => 'Intel Z97',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 3100/2933/2800/2400/2133/1866/1600/1333/1066',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '3',
    'PCI Slots' => '2',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 1,
  ),


  274 => 
  array (
    'Brand' => 'Asus',
    'Model' => 'M5A97 LE R2.0',
    ' CPU Socket Type' => 'AM3+',
    'CPU Type' => 'FX / Phenom II / Athlon II / Sempron 100 Series',
    ' Chipset' => 'AMD 970',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 2133/1866/1600/1333/1066',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '2',
    'PCI Slots' => '2',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 1,
  ),
  275 => 
  array (
    'Brand' => 'Asus',
    'Model' => 'SABERTOOTH 990FX R2.0',
    ' CPU Socket Type' => 'AM3+',
    'CPU Type' => 'FX / Phenom II / Athlon II / Sempron 100 Series',
    ' Chipset' => 'AMD 990FX',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 1866/1600/1333/1066',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '1',
    'PCI Slots' => '1',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '8',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => '2',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 3,
  ),
 
  278 => 
  array (
    'Brand' => 'Asus',
    'Model' => 'M5A99X EVO R2.0',
    ' CPU Socket Type' => 'AM3+',
    'CPU Type' => 'FX / Phenom II / Athlon II / Sempron 100 Series',
    ' Chipset' => 'AMD 990X',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 2133/1866/1600/1333/1066',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '2',
    'PCI Slots' => '1',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => '2',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 2,
  ),
  279 => 
  array (
    'Brand' => 'ASRock',
    'Model' => 'Fatal1ty FM2A88X+ Killer',
    ' CPU Socket Type' => 'FM2+/FM2',
    'CPU Type' => 'Athlon/A- Series (FM2+)',
    ' Chipset' => 'AMD A88X',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 2600/2400/2133/1866/1600/1333/1066',
    'Maximum Memory Supported' => '64',
    'PCI Express x1' => '2',
    'PCI Slots' => '3',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '8',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 1,
  ),
  
  281 => 
  array (
    'Brand' => 'MSI',
    'Model' => '970 Gaming',
    ' CPU Socket Type' => 'AM3+/AM3',
    'CPU Type' => 'FX / Phenom II / Athlon II and Sempron',
    ' Chipset' => 'AMD 970',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 2133/1866/1600/1333/1066',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '2',
    'PCI Slots' => '2',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 2,
  ),
 
  283 => 
  array (
    'Brand' => 'Asus',
    'Model' => 'M5A99FX PRO R2.0',
    ' CPU Socket Type' => 'AM3+',
    'CPU Type' => 'FX / Phenom II / Athlon II / Sempron 100 Series',
    ' Chipset' => 'AMD 990FX',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 2133/1866/1600/1333/1066',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '1',
    'PCI Slots' => '1',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '5',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => '1',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 2,
  ),
  284 => 
  array (
    'Brand' => 'MSI',
    'Model' => '970A-G43 Plus',
    ' CPU Socket Type' => 'AM3+/AM3',
    'CPU Type' => 'Phenom FX / Phenom / Athlon / Sempron',
    ' Chipset' => 'AMD 970',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 2133/1866/1600/1333/1066',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '2',
    'PCI Slots' => '2',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 2,
  ),


  289 => 
  array (
    'Brand' => 'MSI',
    'Model' => '970A SLI Krait Edition',
    ' CPU Socket Type' => 'AM3+',
    'CPU Type' => 'AMD FX/ Processors, and Intel Phenom II/ Athlon II and Sempron',
    ' Chipset' => 'AMD 970',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 2133/1866/1600/1333/1066',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '2',
    'PCI Slots' => '2',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 2,
  ),
  290 => 
  array (
    'Brand' => 'MSI',
    'Model' => '990FXA-GAMING',
    ' CPU Socket Type' => 'AM3+/AM3',
    'CPU Type' => 'AMD FX/ Phenom II/ Athlon II and Sempron',
    ' Chipset' => 'AMD 990FX',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 2133/1866/1600/1333/1066',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '2',
    'PCI Slots' => '1',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 3,
  ),

  299 => 
  array (
    'Brand' => 'Asus',
    'Model' => 'M5A97 PLUS',
    ' CPU Socket Type' => 'AM3+',
    'CPU Type' => 'FX / Phenom II / Athlon II / Sempron 100 Series',
    ' Chipset' => 'AMD 970',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 2133/1866/1600/1333/1066',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '2',
    'PCI Slots' => '3',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 1,
  ),
  300 => 
  array (
    'Brand' => 'ASRock',
    'Model' => '990FX Extreme3',
    ' CPU Socket Type' => 'AM3+',
    'CPU Type' => 'FX / Phenom II / Athlon II / Sempron 100 Series',
    ' Chipset' => 'AMD 990FX',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 2100/1866/1600/1333/1066/800',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '1',
    'PCI Slots' => '2',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '5',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => '1',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 3,
  ),


  310 => 
  array (
    'Brand' => 'ASRock',
    'Model' => '970 PRO3 R2.0',
    ' CPU Socket Type' => 'AM3+',
    
    ' Chipset' => 'AMD 970',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 2100/1866/1800/1600/1333/1066/800',
    'Maximum Memory Supported' => '64',
    'PCI Express x1' => '1',
    'PCI Slots' => '2',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '20Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 2,
  ),
  311 => 
  array (
    'Brand' => 'MSI',
    'Model' => '970A-G46',
    ' CPU Socket Type' => 'AM3+/AM3',
    'CPU Type' => 'FX, Phenom II X6/X4/X3/X2, Athlon II X4/X3/X2 and Sempron',
    ' Chipset' => 'AMD 970',
    'Number of Memory Slots' => '4',
    'Memory Standard' => 'DDR3 2133/1866/1600/1333/1066/800',
    'Maximum Memory Supported' => '32',
    'PCI Express x1' => '2',
    'PCI Slots' => '2',
    'PCI Express x4' => 'Null',
    'PCI Express x8' => 'Null',
    ' SATA 6Gb/s' => '6',
    'SATA RAID' => 0,
    'M.2' => 'Null',
    'SATA Express' => 'Null',
    'eSATA' => 'Null',
    ' SATA 3Gb/s' => 'Null',
    ' mSATA' => 'Null',
    'Max LAN Speed' => '10/100/1000Mbps',
    'Onboard USB' => 1,
    'Form Factor' => 'ATX',
    'Power Pin' => '24Pin',
    'memory pin' => '240-pin',
    'pci_x16_slot' => 2,
  ),



];


echo "<pre>";
var_export($mobo);
echo "</pre>";

